version: "3.2"
services:
  postgres-social-dev:
    build:
      context: ../../../
      dockerfile: ./postgres/Dockerfile
    container_name: postgres-social-dev
    environment:
      POSTGRES_DB: dev_social
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    expose:
      - "5440"
    ports:
      - "5440:5440"
    command: -p 5440

  social-dev:
    build:
      context: ../../../
      dockerfile: ./projects/back/dev/Dockerfile
    container_name: social-dev
    ports:
      - "5561:5561"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-social-dev:5434/dev_social?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 5561
    depends_on:
      - postgres-social-dev
